# Generated by Django 3.0.7 on 2020-07-05 21:45

import django.contrib.postgres.fields.hstore
from django.db import migrations
import restaurant_management_django.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutritional_values',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, validators=[restaurant_management_django.products.models.validate_format, restaurant_management_django.products.models.validate_value_exists], verbose_name='Nutritional values of the product'),
        ),
    ]
