# Generated by Django 3.0.7 on 2020-07-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of nutritional information')),
                ('unit', models.CharField(max_length=8, verbose_name='Unit')),
            ],
        ),
    ]
