# Generated by Django 3.0.7 on 2020-07-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='unit',
            field=models.CharField(max_length=16, verbose_name='Unit'),
        ),
    ]
